version: "3.8"

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    image: saturn_mysql_image
    container_name: saturn_mysql_container
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: abcd@1234
      MYSQL_DATABASE: saturn_db

    ports:
      - "3306:3306"
      
    volumes:
      - ./db:/var/lib/mysql
      - ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
